### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ricglz** [ricglz/ttt-react#19]
It would be nice that there would be more translations of messages, so if you want to add a new language you will have to add a new file or enhance the current ones

**Comment by izanf** [comment]
#20

**Comment by WarleyFranco** [comment]
Can I help translate to Portuguese (pt-br), 
I'll sending PR soon.

**Comment by angelobms** [comment]
Added translate to portuguese/brazil (pt-br). #33

**Comment by Yathousen** [comment]
Hi @ricglz0201 , i'll take care of Russian and Swedish translation.

**Comment by rapirent** [comment]
I'll translate to Traditional Chinese
